{"ast":null,"code":"/**\r\n * Copyright (c) Facebook, Inc. and its affiliates.\r\n *\r\n * This source code is licensed under the MIT license found in the\r\n * LICENSE file in the root directory of this source tree.\r\n *\r\n * \r\n */\nimport invokeGuardedCallbackImpl from './invokeGuardedCallbackImpl'; // Used by Fiber to simulate a try-catch.\n\nlet hasError = false;\nlet caughtError = null; // Used by event system to capture/rethrow the first error.\n\nlet hasRethrowError = false;\nlet rethrowError = null;\nconst reporter = {\n  onError(error) {\n    hasError = true;\n    caughtError = error;\n  }\n\n};\n/**\r\n * Call a function while guarding against errors that happens within it.\r\n * Returns an error if it throws, otherwise null.\r\n *\r\n * In production, this is implemented using a try-catch. The reason we don't\r\n * use a try-catch directly is so that we can swap out a different\r\n * implementation in DEV mode.\r\n *\r\n * @param {String} name of the guard to use for logging or debugging\r\n * @param {Function} func The function to invoke\r\n * @param {*} context The context to use when calling the function\r\n * @param {...*} args Arguments for function\r\n */\n\nexport function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {\n  hasError = false;\n  caughtError = null;\n  invokeGuardedCallbackImpl.apply(reporter, arguments);\n}\n/**\r\n * Same as invokeGuardedCallback, but instead of returning an error, it stores\r\n * it in a global so it can be rethrown by `rethrowCaughtError` later.\r\n * TODO: See if caughtError and rethrowError can be unified.\r\n *\r\n * @param {String} name of the guard to use for logging or debugging\r\n * @param {Function} func The function to invoke\r\n * @param {*} context The context to use when calling the function\r\n * @param {...*} args Arguments for function\r\n */\n\nexport function invokeGuardedCallbackAndCatchFirstError(name, func, context, a, b, c, d, e, f) {\n  invokeGuardedCallback.apply(this, arguments);\n\n  if (hasError) {\n    const error = clearCaughtError();\n\n    if (!hasRethrowError) {\n      hasRethrowError = true;\n      rethrowError = error;\n    }\n  }\n}\n/**\r\n * During execution of guarded functions we will capture the first error which\r\n * we will rethrow to be handled by the top level error handler.\r\n */\n\nexport function rethrowCaughtError() {\n  if (hasRethrowError) {\n    const error = rethrowError;\n    hasRethrowError = false;\n    rethrowError = null;\n    throw error;\n  }\n}\nexport function hasCaughtError() {\n  return hasError;\n}\nexport function clearCaughtError() {\n  if (hasError) {\n    const error = caughtError;\n    hasError = false;\n    caughtError = null;\n    return error;\n  } else {\n    throw new Error('clearCaughtError was called but no error was captured. This error ' + 'is likely caused by a bug in React. Please file an issue.');\n  }\n}","map":{"version":3,"names":["invokeGuardedCallbackImpl","hasError","caughtError","hasRethrowError","rethrowError","reporter","onError","error","invokeGuardedCallback","name","func","context","a","b","c","d","e","f","apply","arguments","invokeGuardedCallbackAndCatchFirstError","clearCaughtError","rethrowCaughtError","hasCaughtError","Error"],"sources":["D:/project/font-end/debug-anything/react-test/src/react/packages/shared/ReactErrorUtils.js"],"sourcesContent":["/**\r\n * Copyright (c) Facebook, Inc. and its affiliates.\r\n *\r\n * This source code is licensed under the MIT license found in the\r\n * LICENSE file in the root directory of this source tree.\r\n *\r\n * @flow\r\n */\r\n\r\nimport invokeGuardedCallbackImpl from './invokeGuardedCallbackImpl';\r\n\r\n// Used by Fiber to simulate a try-catch.\r\nlet hasError: boolean = false;\r\nlet caughtError: mixed = null;\r\n\r\n// Used by event system to capture/rethrow the first error.\r\nlet hasRethrowError: boolean = false;\r\nlet rethrowError: mixed = null;\r\n\r\nconst reporter = {\r\n  onError(error: mixed) {\r\n    hasError = true;\r\n    caughtError = error;\r\n  },\r\n};\r\n\r\n/**\r\n * Call a function while guarding against errors that happens within it.\r\n * Returns an error if it throws, otherwise null.\r\n *\r\n * In production, this is implemented using a try-catch. The reason we don't\r\n * use a try-catch directly is so that we can swap out a different\r\n * implementation in DEV mode.\r\n *\r\n * @param {String} name of the guard to use for logging or debugging\r\n * @param {Function} func The function to invoke\r\n * @param {*} context The context to use when calling the function\r\n * @param {...*} args Arguments for function\r\n */\r\nexport function invokeGuardedCallback<A, B, C, D, E, F, Context>(\r\n  name: string | null,\r\n  func: (a: A, b: B, c: C, d: D, e: E, f: F) => mixed,\r\n  context: Context,\r\n  a: A,\r\n  b: B,\r\n  c: C,\r\n  d: D,\r\n  e: E,\r\n  f: F,\r\n): void {\r\n  hasError = false;\r\n  caughtError = null;\r\n  invokeGuardedCallbackImpl.apply(reporter, arguments);\r\n}\r\n\r\n/**\r\n * Same as invokeGuardedCallback, but instead of returning an error, it stores\r\n * it in a global so it can be rethrown by `rethrowCaughtError` later.\r\n * TODO: See if caughtError and rethrowError can be unified.\r\n *\r\n * @param {String} name of the guard to use for logging or debugging\r\n * @param {Function} func The function to invoke\r\n * @param {*} context The context to use when calling the function\r\n * @param {...*} args Arguments for function\r\n */\r\nexport function invokeGuardedCallbackAndCatchFirstError<\r\n  A,\r\n  B,\r\n  C,\r\n  D,\r\n  E,\r\n  F,\r\n  Context,\r\n>(\r\n  name: string | null,\r\n  func: (a: A, b: B, c: C, d: D, e: E, f: F) => void,\r\n  context: Context,\r\n  a: A,\r\n  b: B,\r\n  c: C,\r\n  d: D,\r\n  e: E,\r\n  f: F,\r\n): void {\r\n  invokeGuardedCallback.apply(this, arguments);\r\n  if (hasError) {\r\n    const error = clearCaughtError();\r\n    if (!hasRethrowError) {\r\n      hasRethrowError = true;\r\n      rethrowError = error;\r\n    }\r\n  }\r\n}\r\n\r\n/**\r\n * During execution of guarded functions we will capture the first error which\r\n * we will rethrow to be handled by the top level error handler.\r\n */\r\nexport function rethrowCaughtError() {\r\n  if (hasRethrowError) {\r\n    const error = rethrowError;\r\n    hasRethrowError = false;\r\n    rethrowError = null;\r\n    throw error;\r\n  }\r\n}\r\n\r\nexport function hasCaughtError() {\r\n  return hasError;\r\n}\r\n\r\nexport function clearCaughtError() {\r\n  if (hasError) {\r\n    const error = caughtError;\r\n    hasError = false;\r\n    caughtError = null;\r\n    return error;\r\n  } else {\r\n    throw new Error(\r\n      'clearCaughtError was called but no error was captured. This error ' +\r\n        'is likely caused by a bug in React. Please file an issue.',\r\n    );\r\n  }\r\n}\r\n"],"mappings":"AAAA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AAEA,OAAOA,yBAAP,MAAsC,6BAAtC,C,CAEA;;AACA,IAAIC,QAAiB,GAAG,KAAxB;AACA,IAAIC,WAAkB,GAAG,IAAzB,C,CAEA;;AACA,IAAIC,eAAwB,GAAG,KAA/B;AACA,IAAIC,YAAmB,GAAG,IAA1B;AAEA,MAAMC,QAAQ,GAAG;EACfC,OAAO,CAACC,KAAD,EAAe;IACpBN,QAAQ,GAAG,IAAX;IACAC,WAAW,GAAGK,KAAd;EACD;;AAJc,CAAjB;AAOA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;;AACA,OAAO,SAASC,qBAAT,CACLC,IADK,EAELC,IAFK,EAGLC,OAHK,EAILC,CAJK,EAKLC,CALK,EAMLC,CANK,EAOLC,CAPK,EAQLC,CARK,EASLC,CATK,EAUC;EACNhB,QAAQ,GAAG,KAAX;EACAC,WAAW,GAAG,IAAd;EACAF,yBAAyB,CAACkB,KAA1B,CAAgCb,QAAhC,EAA0Cc,SAA1C;AACD;AAED;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;;AACA,OAAO,SAASC,uCAAT,CASLX,IATK,EAULC,IAVK,EAWLC,OAXK,EAYLC,CAZK,EAaLC,CAbK,EAcLC,CAdK,EAeLC,CAfK,EAgBLC,CAhBK,EAiBLC,CAjBK,EAkBC;EACNT,qBAAqB,CAACU,KAAtB,CAA4B,IAA5B,EAAkCC,SAAlC;;EACA,IAAIlB,QAAJ,EAAc;IACZ,MAAMM,KAAK,GAAGc,gBAAgB,EAA9B;;IACA,IAAI,CAAClB,eAAL,EAAsB;MACpBA,eAAe,GAAG,IAAlB;MACAC,YAAY,GAAGG,KAAf;IACD;EACF;AACF;AAED;AACA;AACA;AACA;;AACA,OAAO,SAASe,kBAAT,GAA8B;EACnC,IAAInB,eAAJ,EAAqB;IACnB,MAAMI,KAAK,GAAGH,YAAd;IACAD,eAAe,GAAG,KAAlB;IACAC,YAAY,GAAG,IAAf;IACA,MAAMG,KAAN;EACD;AACF;AAED,OAAO,SAASgB,cAAT,GAA0B;EAC/B,OAAOtB,QAAP;AACD;AAED,OAAO,SAASoB,gBAAT,GAA4B;EACjC,IAAIpB,QAAJ,EAAc;IACZ,MAAMM,KAAK,GAAGL,WAAd;IACAD,QAAQ,GAAG,KAAX;IACAC,WAAW,GAAG,IAAd;IACA,OAAOK,KAAP;EACD,CALD,MAKO;IACL,MAAM,IAAIiB,KAAJ,CACJ,uEACE,2DAFE,CAAN;EAID;AACF"},"metadata":{},"sourceType":"module"}